[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "episcope"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "typer",
    "requests",
    "numpy",
    "scikit-learn",
    "pandas",
    "python-dotenv",
    "torch",
    "transformers",
    "sentence-transformers",
    "faiss-cpu",
    "qdrant-client",
    "unstructured",
    "openai",
    "google-genai",
    "rapidfuzz",
    "lxml",
    "pymongo",
]

[project.scripts]
episcope = "episcope.episcope:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
