[tox]
minversion = 3.10.0
envlist = python3.10, python3.11, python3.12, python3.13, python3.14, ruff, ty
isolated_build = True

[gh-actions]
python =
    3.10: python3.10, ruff, ty
    3.11: python3.11
    3.12: python3.12
    3.13: python3.13
    3.14: python3.14


[testenv]
extras =
    eval
deps =
    pytest==9.0.3
commands = pytest tests --basetemp={envtmpdir}

[testenv:ty]
description = run ty type checker
basepython = python3.10
skip_install = true # avoids installing the package and its dependencies, since ty only needs to check the code and doesn't need to run it
deps =
    ty==0.0.35
commands =
    ty check src/episcope --extra-search-path src --exit-zero # exit-zero to avoid CI on things that are not typed yet

[testenv:ruff]
description = run ruff linter
basepython = python3.10
skip_install = true # avoids installing the package and its dependencies, since ruff only needs to check the code and doesn't need to run it
deps =
    ruff==0.15.11
commands =
    ruff check src/episcope tests
